#!/usr/bin/bash

# (C) NORCE Climate
# Tyge Løvset, Feb. 2020


__cleanup()
{
    if [ -f $FILE.tmp ]; then
      rm $FILE.tmp
      echo Removed temp file.
    fi
}

trap __cleanup EXIT

TOOL=ncdu2
BASE=index.ncdu
DIR=$(dirname $0)
DEFAULT=$BASE.w$(date +%V)
FILE=$DEFAULT.gz
CREATE=0
IMPORT=0
SCAN=0
HELP=0
POSITIONAL=()

while [[ $# -gt 0 ]]
do
  key="$1"
  case $key in
    -z|--gzfile)
    FILE="$2"
    shift # past argument
    shift # past value
    ;;
    -i|--import)
    IMPORT=1
    shift # past argument
    ;;
    -s|--save)
    CREATE=1
    shift # past argument
    ;;
    -S)
    CREATE=2
    shift # past argument
    ;;  
    -m|--memory)
    SCAN=1
    shift # past argument
    ;;
    -h|--help)
    HELP=1
    POSITIONAL+=("$1") # pass it through
    shift # past argument
    ;;    
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
  esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ $HELP == 1 ]; then
   echo "`basename $0` {-i|-s|-S|-m} [-z indexfile]"
   echo "  -h, --help                 This help"
   echo "  -z file, --gzfile file     Gzipped file index. Default $DEFAULT.gz"
   echo "  -i, --import               Import index file in $TOOL (default mode)"
   echo "  -s, --save                 Scan folder tree, export new index file and quit"
   echo "  -S                         Scan folder tree, export new index, import it in $TOOL"
   echo "  -m, --memory               Scan folder tree without saving index, open $TOOL"
   echo ""
   $DIR/$TOOL --help
elif [ $CREATE != 0 ]; then
   if [ -f $FILE ]; then
     echo $FILE already exist.
     exit
   fi
   $DIR/$TOOL -1 --exclude .snapshots -o- $* | gzip > $FILE.tmp
   if [ -f $FILE.tmp ]; then
     if [ $FILE == $DEFAULT.gz ]; then
       for f in $BASE.w??.gz; do
         [ ! -d .ncdu ] && mkdir .ncdu
         mv $BASE.w??.gz .ncdu/
         break
       done
     fi
     mv $FILE.tmp $FILE
     if [ $CREATE == 2 ]; then
       gzip -dc $FILE | $DIR/$TOOL -f- $*
     fi
   fi
elif [ $SCAN == 1 ]; then
   $DIR/$TOOL --exclude .snapshots $*
elif [ -f $FILE ]; then
   gzip -dc $FILE | $DIR/$TOOL -f- $*
else
   echo "  No index file '$FILE' to import."
   echo "  Import an index file with: ncduz -z file.gz, or -h for help."
fi
